#Exercise-Rollback
AWSTemplateFormationVersion: 2022-18-7
Description:  Udacity Devops Lesson 4
Resources:
  EC2Instance:
    Type: 'AWS::EC@::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      
      KeyName:  iyke-lesson-4
      ImageId: 'ami-052efd3df9dad4825'
      InstanceType: t2.micro
  
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0